# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # When build finished, will generate this variable
    outputs:
      build-status: ${{ steps.check.outputs.triggered }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install node js 
      - name: Install node.js
        uses: actions/setup-node@v2.4.0
        with:
            node-version: '14.x'
      
      # Install repo packages
      - name: Install packages
        run: yarn install
      
      # Buidl packages
      - name: Build website
        run: yarn build
        
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{success() && github.ref == 'refs/heads/master'}}
    steps:
#       - name: Checkout
#         uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
      - uses: wshihadeh/docker-deployment-action@v1
        with:
          pre_deployment_command_args: 'git clone https://github.com/thehunterscompany/thc-web/ . && git pull'
          remote_docker_host: dockerUser@thcsas.com.co
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /usr/local/app/thc-web
          stack_file_name: docker-compose.yaml
          keep_files: 5
          args: up -d --build
          
         
  

